"""Unit tests for :mod:`usvote.apportionment` (#182).

The mapping's whole risk is that it *looks* like arithmetic. Two plausible formulas are
wrong — nearest-decade rounding and a bare decade lag — so the tests here are built around
an oracle that owes nothing to the implementation: a **hand-written literal** of all 51
elections, transcribed from apportionment history rather than generated by the function
under test. That discipline is this repo's own (``HYBRID_SUMMARY_COLUMNS``): an assert
built from the thing it checks passes under any change to it.

The cross-check against real allotments lives in
``tests/integration/test_census_conform.py`` and needs a live warehouse, because
``total_electoral_votes`` exists only in ``dwh.votes`` — the committed roster fixture
deliberately carries no counts (D024 §5).
"""

from __future__ import annotations

import pytest

from usvote.apportionment import (
    APPORTIONMENT_LAG_YEARS,
    FIRST_APPORTIONMENT_CENSUS,
    GOVERNING_CENSUS_BY_ELECTION,
    NO_APPORTIONMENT_CENSUSES,
    ApportionmentError,
    governing_census_by_election,
    governing_census_year,
)
from usvote.years import ec_ingest_years

# The oracle: every in-scope election and the census whose apportionment governed it,
# written out by hand. Do NOT regenerate this from `governing_census_year` — it exists
# precisely to be an independent statement of the answer.
#
# Read the 1910 run: FIVE elections (1912-1928) share one census, the longest run in the
# series, because the 1920 census produced no apportionment. Every other census governs
# two or three.
EXPECTED_GOVERNING_CENSUS: dict[int, int] = {
    1824: 1820, 1828: 1820,
    1832: 1830, 1836: 1830, 1840: 1830,
    1844: 1840, 1848: 1840,
    1852: 1850, 1856: 1850, 1860: 1850,
    1864: 1860, 1868: 1860,
    1872: 1870, 1876: 1870, 1880: 1870,
    1884: 1880, 1888: 1880,
    1892: 1890, 1896: 1890, 1900: 1890,
    1904: 1900, 1908: 1900,
    1912: 1910, 1916: 1910, 1920: 1910, 1924: 1910, 1928: 1910,
    1932: 1930, 1936: 1930, 1940: 1930,
    1944: 1940, 1948: 1940,
    1952: 1950, 1956: 1950, 1960: 1950,
    1964: 1960, 1968: 1960,
    1972: 1970, 1976: 1970, 1980: 1970,
    1984: 1980, 1988: 1980,
    1992: 1990, 1996: 1990, 2000: 1990,
    2004: 2000, 2008: 2000,
    2012: 2010, 2016: 2010, 2020: 2010,
    2024: 2020,
}


class TestTheFullSeries:
    def test_the_mapping_matches_the_hand_written_oracle(self) -> None:
        assert GOVERNING_CENSUS_BY_ELECTION == EXPECTED_GOVERNING_CENSUS

    def test_the_oracle_covers_every_in_scope_election(self) -> None:
        # If the spine admits a year (D010's pre-12A epic is the next candidate), this
        # test fails until the oracle above is extended by hand — which is the point.
        assert set(EXPECTED_GOVERNING_CENSUS) == ec_ingest_years()

    def test_there_are_fifty_one_elections(self) -> None:
        assert len(EXPECTED_GOVERNING_CENSUS) == 51

    def test_every_governing_census_precedes_its_election_by_at_least_the_lag(
        self,
    ) -> None:
        for election, census in EXPECTED_GOVERNING_CENSUS.items():
            assert census + APPORTIONMENT_LAG_YEARS <= election

    def test_the_mapping_never_regresses_as_elections_advance(self) -> None:
        # Monotonic non-decreasing: an apportionment once in force is never replaced by an
        # older one.
        seen = [EXPECTED_GOVERNING_CENSUS[y] for y in sorted(EXPECTED_GOVERNING_CENSUS)]
        assert seen == sorted(seen)


class TestTheSharpCases:
    """The cases the issue names, plus the two the 1920 gap creates."""

    @pytest.mark.parametrize(
        ("election", "census"),
        [
            (2020, 2010),  # the AC's headline: NOT 2020
            (2024, 2020),  # the 2020 census first governs here
            (1924, 1910),  # the 1920 gap: NOT 1920
            (1928, 1910),  # still 1910, a decade later
            (1932, 1930),  # the Reapportionment Act of 1929 takes effect
            (1868, 1860),  # Reconstruction, per the AC
            (1872, 1870),  # the 1870 census governs its own C+2 election
            (1912, 1910),  # C+2 is a presidential year, so the lag is 2 not 4
            (1824, 1820),  # the spine floor
        ],
    )
    def test_named_case(self, election: int, census: int) -> None:
        assert governing_census_year(election) == census


class TestTheWrongEasyAnswers:
    """Regressions against the two formulas a future simplification would reach for."""

    def test_nearest_decade_rounding_is_wrong(self) -> None:
        naive = (2020 // 10) * 10
        assert naive == 2020
        assert governing_census_year(2020) == 2010 != naive

    def test_a_bare_decade_lag_with_no_exception_set_is_wrong(self) -> None:
        naive = ((1924 - APPORTIONMENT_LAG_YEARS) // 10) * 10
        assert naive == 1920
        assert governing_census_year(1924) == 1910 != naive

    def test_the_two_formulas_disagree_with_the_truth_on_exactly_these_years(
        self,
    ) -> None:
        def nearest_decade(year: int) -> int:
            return (year // 10) * 10

        def bare_lag(year: int) -> int:
            return ((year - APPORTIONMENT_LAG_YEARS) // 10) * 10

        wrong_nearest = {
            y for y, c in EXPECTED_GOVERNING_CENSUS.items() if nearest_decade(y) != c
        }
        wrong_lag = {
            y for y, c in EXPECTED_GOVERNING_CENSUS.items() if bare_lag(y) != c
        }
        # Nearest-decade rounding fails on exactly two shapes, and naming them is worth
        # more than a count: every election held *in* a census year (the census is taken
        # in the spring and apportioned years later, so it governs nothing yet), plus the
        # two elections the 1920 gap displaces.
        census_year_elections = {
            y for y in EXPECTED_GOVERNING_CENSUS if y % 10 == 0
        }
        assert wrong_nearest == census_year_elections | {1924, 1928}
        assert len(wrong_nearest) == 12
        assert 2020 in wrong_nearest
        # A bare lag gets every one of those right except the 1920 gap, which is the whole
        # residual this module exists for.
        assert wrong_lag == {1924, 1928}


class TestTheNineteenTwentyException:
    def test_1920_is_the_only_no_apportionment_census(self) -> None:
        assert set(NO_APPORTIONMENT_CENSUSES) == {1920}

    def test_no_election_is_governed_by_1920(self) -> None:
        assert 1920 not in set(GOVERNING_CENSUS_BY_ELECTION.values())

    def test_the_1910_apportionment_governs_five_elections(self) -> None:
        on_1910 = sorted(
            y for y, c in GOVERNING_CENSUS_BY_ELECTION.items() if c == 1910
        )
        assert on_1910 == [1912, 1916, 1920, 1924, 1928]

    def test_the_1910_run_is_the_longest_in_the_series(self) -> None:
        counts: dict[int, int] = {}
        for census in GOVERNING_CENSUS_BY_ELECTION.values():
            counts[census] = counts.get(census, 0) + 1
        assert counts[1910] == 5
        assert max(counts.values()) == 5
        assert [c for c, n in counts.items() if n == 5] == [1910]

    def test_removing_the_exception_would_change_exactly_two_elections(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # Guards the constant's reach: if someone empties it, these two years move.
        monkeypatch.setattr(
            "usvote.apportionment.NO_APPORTIONMENT_CENSUSES", frozenset()
        )
        changed = {
            y
            for y in EXPECTED_GOVERNING_CENSUS
            if governing_census_year(y) != EXPECTED_GOVERNING_CENSUS[y]
        }
        assert changed == {1924, 1928}


class TestTheLagConstant:
    """Survivor 1 (#182 Class B): `APPORTIONMENT_LAG_YEARS = 2 -> 1` survived the suite.

    Four tests mentioned the lag and **three were circular** — they asserted
    `census + APPORTIONMENT_LAG_YEARS <= election`, computed `first = FIRST + LAG`, or defined
    their "naive" formula in terms of the constant, so the expectation moved with the mutation
    and the assertion stayed true. The fourth, the 51-year oracle, is genuinely independent and
    does kill a wrong lag in general (it kills `lag = 4`) — but it is arithmetically blind to
    this one perturbation: floor-to-decade makes lags 1 and 2 identical on every year
    congruent to 0, 2, 4, 6 or 8 mod 10, which is every presidential election year.

    So the lag needs a pin that does not go through the mapping at all, plus the boundary case
    the mapping cannot reach.
    """

    def test_the_lag_is_pinned_to_a_literal(self) -> None:
        # Hand-written, not derived. The `HYBRID_SUMMARY_COLUMNS` discipline: an assertion
        # written in terms of the constant cannot detect a change to it.
        assert APPORTIONMENT_LAG_YEARS == 2
        assert FIRST_APPORTIONMENT_CENSUS == 1790

    def test_the_raise_boundary_is_pinned_without_reference_to_the_constant(self) -> None:
        # The one place the lag is observable outside the 4-yearly grid. With lag 1,
        # governing_census_year(1791) returns 1790 instead of raising -- the mapping over
        # election years is unchanged, so only a literal year catches it.
        assert governing_census_year(1792) == 1790
        with pytest.raises(ApportionmentError):
            governing_census_year(1791)


class TestOutOfRange:
    def test_1789_raises_rather_than_returning_a_floor(self) -> None:
        # The 1789 allotment came from Art. I, section 2 -- not from an enumeration. A
        # floor value here would silently divide 1789 electors by 1790 population.
        with pytest.raises(ApportionmentError, match="1789"):
            governing_census_year(1789)

    def test_the_first_governed_election_is_the_census_plus_the_lag(self) -> None:
        first = FIRST_APPORTIONMENT_CENSUS + APPORTIONMENT_LAG_YEARS
        assert governing_census_year(first) == FIRST_APPORTIONMENT_CENSUS
        with pytest.raises(ApportionmentError):
            governing_census_year(first - 1)


class TestInjectableScope:
    def test_years_is_injectable(self) -> None:
        assert governing_census_by_election({1924, 2024}) == {1924: 1910, 2024: 2020}

    def test_the_default_is_the_spine_scope(self) -> None:
        assert governing_census_by_election() == GOVERNING_CENSUS_BY_ELECTION

    def test_an_empty_scope_yields_an_empty_mapping(self) -> None:
        assert governing_census_by_election(set()) == {}
